Init guide line ios tutorial
framgia/Training-Guideline pull request #66
Opened 2021-10-29 07:39 UTC by tuanlvt-1117

IOS Tutorial

2021-11-01 08:19 UTC, daolq-2712 requested changes
Pls check my comment!

2021-11-01 08:19 UTC, daolq-2712 commented on IOS/ios_tutorial.md
> +* Book: https://sal.vn/w40e9A
```suggestion
* Book: 
  **Swift 4**: https://sal.vn/xxXB0y
  **IOS**: https://sal.vn/a4v0Ou
```

2021-11-01 08:19 UTC, daolq-2712 commented on IOS/ios_tutorial_en.md
> +* Book: https://sal.vn/w40e9A
```suggestion
* Book: 
  **Swift 4**: https://sal.vn/xxXB0y
  **IOS**: https://sal.vn/a4v0Ou
```

2021-11-01 08:41 UTC, vietnh-1109 approved these changes

2021-11-02 00:56 UTC, daolq-2712 approved these changes
LGTM!

2021-11-02 00:56 UTC, merged